apiRules:
- include: # The namespaces to generate
    uidRegex: ^Tetris
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .* # Every other namespaces are ignored
    type: Namespace